In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
def onemax(x):
  return x.sum()

In [ ]:
def generate_binary(D):
  ## Generate a array of D bits
  return np.random.randint(0, 11, D)

for i in range(5):
  x = generate_binary(10)
  y = onemax(x)

  print(f"{x} + {y}")


[ 6  3  0 10  2  1  8  7  7  8] + 52
[ 2  5  0  9  1  7  6  4  3 10] + 47
[6 7 9 9 8 5 8 6 1 1] + 60
[5 3 6 3 4 0 3 6 9 3] + 42
[ 2  2 10 10  6 10  7  8  6  5] + 66


In [ ]:
def binary_mutation(parent):
  idx = np.random.randint(parent.shape[0])

  child = parent.copy()
  child[idx] = abs(parent[idx] - 1)

  return child

In [ ]:
def greater_than_equal(a, b):
  return a >= b

In [ ]:
def hillclimber(Niter, problem, D, generate_binary, mutation, comparsion):
  parent = generate_binary(D)
  parent_fitness = problem(parent)

  for iter in range(Niter):
    child = mutation(parent)


  child_fitness = problem(child)

  if comparsion(child_fitness, parent_fitness):
    parent = child
    parent_fitness = child_fitness

  return parent, parent_fitness

In [ ]:
x, y = hillclimber(30, onemax, 10, generate_binary, binary_mutation, greater_than_equal)
print(f"Best Solution: {x}, fitness: {y}")

Best Solution: [ 1  0  1  6 10  7  0  9  4  3], fitness: 41


In [ ]:
def sphere(x):
  return (x**2).sum()

In [ ]:
def generate_continuous(D):

  return np.random.randint(-3, 3, D)
    
    
  for i in range(5):
    x = generate_continuous(3)
    y = sphere(x)
    print(f"Solution {x}, fitness {y}")

In [ ]:
def additive_gaussian(parent):
  z = np.random.randn() * 0.1
  idx = np.random.randint(parent.shape[0])
  child = parent.copy()
  child[idx] = parent[idx] + z
  return child

In [ ]:
def less_than_equal(a, b):
  return a <= b 

In [ ]:
x, y = hillclimber(3000, sphere, 10, generate_continuous, additive_gaussian, less_than_equal)
print(f"Solution x: {x}, fitness {y}")

Solution x: [ 1  2  1  0 -2  2  0 -2  2  2], fitness 26
